config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :users
  resources :groups do
    resources :bookings, only: [:new, :edit, :create]
    resources :reviews, only: [:show, :new, :create]
  end

  resources :bookings, only: [:show, :destroy]
  resources :reviews, only: [:destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern
  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :bookings
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?



include Filterable

  # scope :user, -> (teacher) { where("teacher ILIKE ?", "%#{style}%") }
  scope :city, -> (city) { where("city ILIKE ?", "%#{city}%") }
  scope :structure, -> (structure) { where(structure: structure) }
  scope :style, -> (style) { where(style: style) }
  # scope :min_price, -> (min_price) { where("price < ?", "#{min_price}") }
  # scope :max_price, -> (max_price) { where("price < ?", "#{max_price}") }





end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :booking
  has_many :reviews
  has_many :groups
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

      before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
  #   devise_paramter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
  # devise_paramter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def new
    @booking = Booking.new
    @group = Group.find(params[:group_id])
  end

   def create
    @group = Group.find(params[:group_id])
    @booking = Booking.new(booking_params)

    @booking.group = @group
    @booking.user = current_user
    if @booking.save!
      redirect_to root_path
    else
      redirect_to new_group_booking_path
    end
    # @purchase.save
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:user_id, :group_id, :date)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 # before_action :load_map, only: [:show, :index]


  def index
    # @groups = Group.all
    @groups = Group.geocoded.filter(params.slice(:address, :structure, :style)).order(created_at: :desc)
    # @groups = Group.geocoded

    @markers = @groups.map do |group|
      {
        lat: group.latitude,
        lng: group.longitude,
        infoWindow: render_to_string(partial: "/groups/info_window", locals: { group: group })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end

  end

  def show
    # @group = Group.find(params[:id])
    # @review = Review.new
    @group = Group.geocoded.find(params[:id])

    # @markers = @groups.map do |group|
    #   {
    #     lat: group.latitude,
    #     lng: group.longitude,
    #     infoWindow: render_to_string(partial: "/groups/info_window", locals: { group: group })
    #     # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
    #   }
      @markers = [{
        lat: @group.latitude,
        lng: @group.longitude,
        infoWindow: render_to_string(partial: "/groups/info_window", locals: { group: @group })
      }]

  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

   def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :content, :city, :style, :address, :structure, :link, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @groups = Group.limit(6).order(created_at: :desc)
  end

  def dashboard
     @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def new
    @group = Group.find(params[:group_id])
    @review = Review.new
  end

  def create
    @group = Group.find(params[:group_id])
    @review = Review.new(review_params)

    @review.group = @group
    @review.user = current_user
    if @review.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def show
  end

   def review_params
    params.require(:review).permit(:user_id, :group_id, :content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user

  end

  def edit
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Sessions#index</h1>
<p>Find me in app/views/sessions/index.html.erb</p>

app/views/bookings/new.html.erb
<div class="container-1" style="margin-top: 80px">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1 class="mb-4">Book a session</h1>
      <%= simple_form_for [@group, @booking] do |f| %>
      <%= f.input :date, label: "Date of your session" %>
      <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <br>
</div>

app/views/bookings/show.html.erb
<h1>Sessions#show</h1>
<p>Find me in app/views/sessions/show.html.erb</p>

app/views/groups/_info_window.html.erb
<h2><%= group.name %></h2>
<p><%= group.address %></p>

app/views/groups/edit.html.erb
<div class="container-1" style="margin-top: 80px">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1 class="mb-4">Create a group</h1>
      <%= simple_form_for [@group] do |f| %>
      <%= f.input :name, label: "Name of your group" %>
      <%= f.input :content, label: "Describe your group", :input_html => {:rows => 5} %>
      <%= f.input :style, label: "Type of meditation", collection: ["Loving-kindness meditation", "Mindfulness meditation", "Buddhist meditation", "Zen meditation", "Transcendental meditation", "Other" ] %>
      <%= f.input :structure, label: "Type of group", collection: ["Group class", "Group meditation", "One-on-one", "Group discussion", "Social Group" ]%>
      <%= f.input :link, label: "Media link to your group" %>
      <%= f.input :address, label: "The group's address" %>
      <%= f.input :city, label: "City", hint: "", placeholder: "e.g London, Cambrdige, Oxford" %>
      <%= link_to "Delete", group_path(@group), method: :delete, class: 'btn btn-danger', style: "margin-bottom: 10px;" %>
      <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <br>
</div>

app/views/groups/index.html.erb
<h1>Check out the groups!</h1>

<div class="container">
  <br>
  <br>

  <%= simple_form_for :search, url: groups_path, method: :get do |f| %>
  <div class="search-form-control form-group form-inline" >
    <input class="form-control string required" id=input-1 type="text" name="named" id="query" placeholder="City" onfocus="" onblur="" <%= params[:address] %> />

    <select name="style" class="form-control string" id="drop-down">
      <option  value="">Style of meditation</option>
      <option value="Loving-kindness meditation">Loving-kindness meditation</option>
      <option value="Mindfulness meditation">Mindfulness meditation</option>
      <option value="Buddhist meditation">Buddhist meditation</option>
      <option value="Zen meditation">Zen meditation</option>
      <option value="Transcendental meditation">Transcendental meditation</option>
      <option value="Other">Other</option>
    </select>

     <select name="structure" class="form-control string" id="drop-down">
      <option  value="">Group structure</option>
      <option value="Group class">Group class</option>
      <option value="One-on-one">One-on-one</option>
      <option value="Group discussion">Group discussion</option>
      <option value="Social Group">Social Group</option>
    </select>

    <button name="button" type="submit" class="btn btn-flat" id="search-button">
     <i class="fas fa-lotus"></i> Search groups
    </button>
  </div>
<% end %>

<div class="cards">
<% @groups.each do |group| %>
<% if group.photo.attached? %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path group.photo.key, crop: :fill %>');">


      <p><%= link_to group.name, group_path(group) %></p>
    </div>
    <% else %>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/1882004/pexels-photo-1882004.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400)">
      <p><%= link_to group.name, group_path(group) %></p>
    </div>
    <% end %>
  <% end %>
  </div>

<br>
<br>
<div
  id="map"
  style="width: 100%;
  height: 400px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
 ></div>



</div>

app/views/groups/new.html.erb
<div class="container-1" style="margin-top: 80px">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1 class="mb-4">Create a group</h1>
      <%= simple_form_for [@group] do |f| %>
      <%= f.input :name, label: "Name of your group" %>
      <%= f.input :content, label: "Describe your group", :input_html => {:rows => 5} %>
      <%= f.input :style, label: "Type of meditation", collection: ["Loving-kindness meditation", "Mindfulness meditation", "Buddhist meditation", "Zen meditation", "Transcendental meditation", "Other" ] %>
      <%= f.input :structure, label: "Type of group", collection: ["Group class", "Group meditation", "One-on-one", "Group discussion", "Social Group" ]%>
      <%= f.input :link, label: "Media link to your group" %>
      <%= f.input :address, label: "The group's address" %>
      <%= f.input :city, label: "City", hint: "", placeholder: "e.g London, Cambrdige, Oxford" %>
      <%= f.input :photo, as: :file, label: "Upload a photo of your group!"%>
      <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <br>
</div>

app/views/groups/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.2)), url('<%= cl_image_path @group.photo.key, crop: :fill %>');">
  <div class="container">
    <h1 style= "font-size: 40px"><%= @group.name %> </h1>
    <br>
  </div>
</div>

<div class="all-info">

  <div class="small-div">

    <div class="group-info">

        <p>Who are we?: <%= @group.content %></p>
        <p>Style: <%= @group.style %></p>
        <p>Structure: <%= @group.structure %></p>
        <p>Group host: <%= @group.user.first_name %></p>

    </div>



      <div
        id="map"
        style="width: 100%;
        height: 400px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
       ></div>

      <div class="group-reviews">
        <% @group.reviews.each do |review| %>
        <%= review.user.first_name %>
        <% end %>

      </div>


<%= link_to "Edit", edit_group_path(@group), class: 'btn btn-primary'%>

<%= link_to "Book a session", new_group_booking_path(@group), class: 'btn btn-primary'%>

<%= link_to "Add a review", new_group_review_path(@group), class: 'btn btn-primary'%>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag 'init_mapbox' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%#= javascript_pack_tag 'init_mapbox' %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<%= cl_image_tag current_user.photo.key, height: 300, width: 400, crop: :fill %>




<h1>My bookings</h1>

<% @user.booking.each do |booking| %>
<p>Group name: <%= booking.group.name %></p>
<p>Booking date: <%= booking.date %></p>
<% end %>

<h1>My groups</h1>


  <% if @user.groups.empty? %>
  <p>You do not have any groups.</p>
  <% else %>
    <% @user.groups.each do |group| %>
    <p>Group name: <%= group.name %></p>
  <% end %>
<% end %>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="container" style="margin-top: 0px; margin-bottom: 20px">
  <br>

  <br>
  <h2 style= "text-align: center;">Find meditation groups in your area
  <br>

<div class="cards">
<% @groups.each do |group| %>

<% if group.photo.attached? %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= cl_image_path group.photo.key, crop: :fill %>');">
      <p><%= link_to group.name, group_path(group) %></p>
      <% else %>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.pexels.com/photos/1882004/pexels-photo-1882004.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=400)">
      <p><%= link_to group.name, group_path(group) %></p>
      <% end %>
    </div>
  <% end %>
  </div>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1 class="text-center">Rate your experience with <%= @group.name %></h1>
<br>

<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= simple_form_for [@group, @review] do |f| %>
        <%= f.input :content, as: :text, label: "Leave your review below" %>
        <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
        <%= f.submit "Submit Review", class: "btn btn-primary m-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.2)), url('<%= image_path "banner.jpg" %>');">
  <div class="container">
    <h1 style= "font-size: 40px">Find meditation groups near you</h1>
    <br>
    <%= render 'shared/search' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", class: "logo"%><span style="padding-left: 16px;">The Meditation Network</span>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Browse groups", groups_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create a group", new_group_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, height: 300, width: 400, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
               <%= link_to "View your dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
            <% else %>
           <%= image_tag "avatar.png", class: "avatar  dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
               <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
               <%= link_to "View your dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
           <% end %>

            <%#= link_to "Action", "#", class: "dropdown-item" %>


        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: groups_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="query" id="query" placeholder="Search city, style or teacher" />
    <button name="button" type="submit" class="btn btn-flat">
      <!-- <i class="fas fa-search"></i> --> <i class="fas fa-lotus"></i> Search groups
    </button>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>My bookings</h1>

<% @user.booking.each do |booking| %>
<p>Group name: <%= booking.group.name %></p>
<p>Booking date: <%= booking.date %></p>


<% end %>